export const TimeLineData = {
    "1": {
        "ID": "1",
        "Type": "Marker",
        "Location": "Above",
        "Start": "800",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "2": {
        "ID": "2",
        "Type": "Event",
        "Location": "Center",
        "Start": "753",
        "End": "",
        "Name": "Rome was founded",
        "Person": "",
        "Subtitle": "",
        "Detail": "Much of what we know about the founding of Rome derives from legend. The story popularized by Virgil in the Aeneid attempts to fuse two myths, the Greek myth of Aeneas and the myth of Romulus and Remus. Virgil describes how Prince Aeneas flees from Troy after the Trojan War and eventually arrives at the banks of the Tiber River, where he establishes a marriage alliance with Lavinia, the daughter of King Latinus. Aeneas marries Lavinia and founds the city of Lavinium; his son Ascanius would found the city of Alba Longa. Many years later, the last king of Alba Longa, King Numitor, would be deposed by his brother Amulius. Romulus and Remus are the grandsons of Numitor through his daughter Rhea Silvia and Mars, the god of war. They were abandoned on the banks of the Tiber, then raised by a she-wolf and a shepherd named Faustulus. Although the two brothers initially intended to found separate cities, a conflict arose between them which ended in Remus's death and the beginnings of what would become Rome.",
        "References": "https://www.britannica.com/topic/Aeneid; https://www.history.com/this-day-in-history/rome-founded"
    },
    "3": {
        "ID": "3",
        "Type": "Marker",
        "Location": "Above",
        "Start": "700",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "4": {
        "ID": "4",
        "Type": "Marker",
        "Location": "Above",
        "Start": "600",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "5": {
        "ID": "5",
        "Type": "Event",
        "Location": "Center",
        "Start": "509",
        "End": "",
        "Name": "Start of Roman Republic",
        "Person": "",
        "Subtitle": "",
        "Detail": "The early Romans derived from mostly Latin heritage. They were ruled by kings, as were many Latin towns and cities. The nobility were organized into the Senate, which advised the king. A series of kings, both Roman and Etruscan, had led Rome's successful expansion among the Latins. However, in the course of the two centuries prior to the establishment of the Roman Republic, royal power had gradually declined in favor of the power of the nobility. The last king, an Etruscan named Lucius Tarquinius Superbus, was a tyrant who brutally suppressed the Senate and precipitated a revolt which effectively ended the monarchy. Instead of a king, two consuls were elected annually to lead the new Roman Republic. The consuls possessed military, administrative, and judicial authority. Of note, the new Republican system allowed for the appointment of dictators with supreme power during six months of military emergency, a fact which would foreshadow Rome's eventual transition into an empire.",
        "References": "https://www.gutenberg.org/files/32624/32624-pdf.pdf; https://www.britannica.com/biography/Tarquin-king-of-Rome-534-509-BC; https://www.worldhistory.org/Lucius_Tarquinius_Superbus/"
    },
    "6": {
        "ID": "6",
        "Type": "Marker",
        "Location": "Above",
        "Start": "500",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "7": {
        "ID": "7",
        "Type": "Event",
        "Location": "Center",
        "Start": "451",
        "End": "",
        "Name": "First written law code",
        "Person": "",
        "Subtitle": "",
        "Detail": "The Law of the Twelve Tables was the first written law code in Rome and marked the transition to  a more egalitarian society. Displayed in the Forum, these laws arose from a growing resentment felt by the plebeian class towards the aristocratic patricians, who wielded extreme power in the Senate. Punishments outlined in the Twelve Tables were applicable to all Roman citizens, and ranged from confiscation of property to death.",
        "References": "https://www.gutenberg.org/files/32624/32624-pdf.pdf; https://www.worldhistory.org/Twelve_Tables/"
    },
    "8": {
        "ID": "8",
        "Type": "Marker",
        "Location": "Above",
        "Start": "400",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "9": {
        "ID": "9",
        "Type": "Event",
        "Location": "Center",
        "Start": "390",
        "End": "",
        "Name": "Sack of Rome by Gallic tribe",
        "Person": "",
        "Subtitle": "",
        "Detail": "Around 390 BCE, the Romans were defeated by the Gallic Senones in a major battle and Rome was sacked. The remnants of the Senate and Roman military fled to the top of the Capitoline Hill, to which the Gauls laid seige for seven months. A Roman dictator, Marcus Furius Camillus, was appointed and finally managed to drive out the Gauls after a series of bloody battles. The effect of this episode was that the Romans realized the inadequacy of their army and thus made great strides in strengthening their military organization as well as the physical fortifications of the city. In the following eight centuries, maintaining the Roman military would become an ever more expensive obligation of the state and contribute to its eventual economic downfall.",
        "References": "https://www.worldhistory.org/article/910/the-sack-of-rome-by-the-gauls-390-bce/"
    },
    "10": {
        "ID": "10",
        "Type": "Event",
        "Location": "Center",
        "Start": "362",
        "End": "",
        "Name": "First plebeian consul elected",
        "Person": "",
        "Subtitle": "",
        "Detail": "In a major win for the plebeians in their struggle for political representation, the first plebeian consul was elected in 362 BCE. IN 340 BCE it became required for at least one consul to be plebeian. During the mid-fourth century BCE, plebeians occupied at various times the positions of the dictatorship, the censorship, and the praetorship, all major political positions within the Roman government. Plebians eventually occupied a large fraction of the Senate, although in some ways class divisions were perpetuated by the fact that only prominent plebian families were represented in these offices.",
        "References": "https://www.gutenberg.org/files/32624/32624-pdf.pdf"
    },
    "11": {
        "ID": "11",
        "Type": "Event",
        "Location": "Center",
        "Start": "340",
        "End": "338",
        "Name": "Second Latin War",
        "Person": "",
        "Subtitle": "",
        "Detail": "As the Romans achieved increasing prominence and power in the Italian peninsula, there was growing discontent among the other Latin city-states. For Rome had begin to consolidate so much power in the so-called Latin League that they became the de facto leader of this military alliance, established some 150 years earlier under the Treaty of Cassius. The Romans took advantage of this alliance to expand their own territories, and after a series of conflicts with the other Latin states eventually absorbed them after the Second Latin War.",
        "References": "https://delong.typepad.com/forsythe-rome.pdf"
    },
    "12": {
        "ID": "12",
        "Type": "Marker",
        "Location": "Above",
        "Start": "300",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "13": {
        "ID": "13",
        "Type": "Event",
        "Location": "Center",
        "Start": "298",
        "End": "290",
        "Name": "Third Samnite War",
        "Person": "",
        "Subtitle": "",
        "Detail": "The Samnites were a resource-poor society living in the Apennine Mountains east of Rome. As they sought to expand into richer lands, they came into conflict with the Romans. The first war between the two societies occurred in 343 BCE, a second war in 326 BCE, and the third and final Samnite War in 298 BCE. During this time, Rome continued to expand, founding sixteen colonies. By the end of the third war, Roman power in Italy was further consolidated.",
        "References": "https://delong.typepad.com/forsythe-rome.pdf"
    },
    "14": {
        "ID": "14",
        "Type": "Coin",
        "Location": "Above",
        "Start": "280",
        "End": "",
        "Name": "Aes signatum",
        "Person": "M. Junius Brutus",
        "Subtitle": "AE Aes signatum",
        "Detail": "Unlike their Greek neighbors, the inhabitants of the Italian peninsula did not enjoy large natural deposits of silver and gold. Thus the earliest Roman currencies were made of bronze (aes) or copper. The aes signatum was a large cast brick of bronze \n\nThis example of an aes signatum exhibits an eagle standing on a thunderbolt on the obverse and a pegasus on the reverse. Both were common Greek motifs, illustrating the heavy Greek influence on early Roman coinage. The reverse inscription ROMANOM, however, makes it clear the identity of the issuers. At 1.39 kilograms, this bronze bar would have been quite cumbersome to transport and ",
        "References": "https://delong.typepad.com/forsythe-rome.pdf; https://webarchive.nationalarchives.gov.uk/ukgwa/20190801144951/https://www.britishmuseum.org/research/publications/online_research_catalogues/search_object_details.aspx?objectid=1171049&partid=1&numpages=12&output=bibliography/!!/OR/!!/6738/!//!/A+catalogue+of+the+Roman+Republican+Coins+in+the+British+Museum,+with+descriptions+and+chronology+based+on+M.H.+Crawford,+Roman+Republican+Coinage+(1974)/!//!!//!!!/&sortBy=catNumber&orig=/research/publications/online_research_catalogues/russian_icons/catalogue_of_russian_icons.aspx&catalogueOnly=True&catparentPageId=29127&catalogueName=Roman%20Republican%20coins%20in%20the%20British%20Museum&catalogueSection=A%20catalogue%20of%20the%20Roman%20Republican%20Coins%20in%20the%20British%20Museum,%20with%20descriptions%20and%20chronology%20based%20on%20M.H.%20Crawford,%20Roman%20Republican%20Coinage%20(1974)&currentPage=1",
        "obverse": "280_aes_signatum_obverse.png",
        "reverse": "280_aes_signatum_reverse.png"
    },
    "15": {
        "ID": "15",
        "Type": "Event",
        "Location": "Center",
        "Start": "280",
        "End": "275",
        "Name": "Pyrrhic War",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "16": {
        "ID": "16",
        "Type": "Coin",
        "Location": "Below",
        "Start": "269",
        "End": "",
        "Name": "Romano-Campanian didrachm",
        "Person": "M. Junius Brutus",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "269_romano-campanian_didrachm_obverse.png",
        "reverse": "269_romano-campanian_didrachm_reverse.png"
    },
    "17": {
        "ID": "17",
        "Type": "Event",
        "Location": "Center",
        "Start": "264",
        "End": "241",
        "Name": "First Punic War",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "18": {
        "ID": "18",
        "Type": "Coin",
        "Location": "Above",
        "Start": "225",
        "End": "",
        "Name": "Aes Grave As",
        "Person": "M. Junius Brutus",
        "Subtitle": "AE Aes Grave",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "225_aes_grave_as_obverse.png",
        "reverse": "225_aes_grave_as_reverse.png"
    },
    "19": {
        "ID": "19",
        "Type": "Coin",
        "Location": "Below",
        "Start": "225",
        "End": "",
        "Name": "Romano-Campanian didrachm",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR Didrachm",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "225_romano-campanian_didrachm_obverse.png",
        "reverse": "225_romano-campanian_didrachm_reverse.png"
    },
    "20": {
        "ID": "20",
        "Type": "Event",
        "Location": "Center",
        "Start": "218",
        "End": "201",
        "Name": "Second Punic War",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "21": {
        "ID": "21",
        "Type": "Coin",
        "Location": "Above",
        "Start": "211",
        "End": "",
        "Name": "Sixty-as coin",
        "Person": "M. Junius Brutus",
        "Subtitle": "AV",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "211_sixty-as_coin_obverse.png",
        "reverse": "211_sixty-as_coin_reverse.png"
    },
    "22": {
        "ID": "22",
        "Type": "Marker",
        "Location": "Above",
        "Start": "200",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "23": {
        "ID": "23",
        "Type": "Event",
        "Location": "Center",
        "Start": "149",
        "End": "146",
        "Name": "Third Punic War",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "24": {
        "ID": "24",
        "Type": "Coin",
        "Location": "Below",
        "Start": "148",
        "End": "",
        "Name": "Denarius of L. Sempronius Pitio",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR Denarius",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "148_denarius_of_l._sempronius_pitio_obverse.png",
        "reverse": "148_denarius_of_l._sempronius_pitio_reverse.png"
    },
    "25": {
        "ID": "25",
        "Type": "Marker",
        "Location": "Above",
        "Start": "100",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "26": {
        "ID": "26",
        "Type": "Coin",
        "Location": "Above",
        "Start": "90",
        "End": "",
        "Name": "Denarius of the Social War",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR Denarius",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "90_denarius_of_the_social_war_obverse.png",
        "reverse": "90_denarius_of_the_social_war_reverse.png"
    },
    "27": {
        "ID": "27",
        "Type": "Event",
        "Location": "Center",
        "Start": "88",
        "End": "",
        "Name": "Sulla marches on Rome",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "28": {
        "ID": "28",
        "Type": "Event",
        "Location": "Center",
        "Start": "63",
        "End": "",
        "Name": "Cicero elected as consul",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "29": {
        "ID": "29",
        "Type": "Event",
        "Location": "Center",
        "Start": "63",
        "End": "",
        "Name": "Pompey captures Syria",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "30": {
        "ID": "30",
        "Type": "Event",
        "Location": "Center",
        "Start": "60",
        "End": "",
        "Name": "First Triumvirate (Caesar, Crassus, & Pompey)",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "31": {
        "ID": "31",
        "Type": "Event",
        "Location": "Center",
        "Start": "58",
        "End": "51",
        "Name": "Caesar conquers Gaul",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "32": {
        "ID": "32",
        "Type": "Event",
        "Location": "Center",
        "Start": "49",
        "End": "",
        "Name": "Caesar crosses the Rubicon",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "33": {
        "ID": "33",
        "Type": "Coin",
        "Location": "Below",
        "Start": "49",
        "End": "",
        "Name": "Denarius of Julius Caesar",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR Denarius",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "49_denarius_of_julius_caesar_obverse.png",
        "reverse": "49_denarius_of_julius_caesar_reverse.png"
    },
    "34": {
        "ID": "34",
        "Type": "Event",
        "Location": "Center",
        "Start": "44",
        "End": "",
        "Name": "Caesar assasinated",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "35": {
        "ID": "35",
        "Type": "Coin",
        "Location": "Above",
        "Start": "43",
        "End": "",
        "Name": "EID MAR coin of Brutus",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "43_eid_mar_coin_of_brutus_obverse.png",
        "reverse": "43_eid_mar_coin_of_brutus_reverse.png"
    },
    "36": {
        "ID": "36",
        "Type": "Coin",
        "Location": "Below",
        "Start": "38",
        "End": "",
        "Name": "Coin of Octavian",
        "Person": "M. Junius Brutus",
        "Subtitle": "AR",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": "",
        "obverse": "38_coin_of_octavian_obverse.png",
        "reverse": "38_coin_of_octavian_reverse.png"
    },
    "37": {
        "ID": "37",
        "Type": "Event",
        "Location": "Center",
        "Start": "31",
        "End": "",
        "Name": "Octavian becomes first Roman emperor",
        "Person": "",
        "Subtitle": "",
        "Detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at augue quis mauris efficitur porta eget vitae metus. Mauris aliquet pharetra velit, eu feugiat arcu blandit a. Nam venenatis tellus sit amet orci tempor commodo. Mauris condimentum, risus sit amet porta blandit, lacus purus lobortis massa, sit amet egestas lorem sapien eget mauris. Phasellus vitae arcu ut risus vulputate tempor. Morbi imperdiet id nulla ac fringilla. In porttitor purus et vulputate convallis. Aliquam ullamcorper est ipsum, et fermentum mauris ornare vitae. Sed id enim risus. Aenean quis ipsum vel nibh bibendum scelerisque sed et justo. Curabitur massa libero, congue non ipsum et, posuere gravida diam. Maecenas sit amet lacus accumsan, ornare purus quis, porta erat. Maecenas sed arcu ac metus aliquam porta. Integer sed nulla scelerisque dolor rutrum faucibus ac nec ante. Aenean sed vehicula nibh.",
        "References": ""
    },
    "38": {
        "ID": "38",
        "Type": "Marker",
        "Location": "Above",
        "Start": "0",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "39": {
        "ID": "39",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "40": {
        "ID": "40",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "41": {
        "ID": "41",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "42": {
        "ID": "42",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "43": {
        "ID": "43",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "44": {
        "ID": "44",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "45": {
        "ID": "45",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "46": {
        "ID": "46",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "47": {
        "ID": "47",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    },
    "48": {
        "ID": "48",
        "Type": "",
        "Location": "",
        "Start": "",
        "End": "",
        "Name": "",
        "Person": "",
        "Subtitle": "",
        "Detail": "",
        "References": ""
    }
}